spring:
  datasource:
    url: jdbc:mysql://118.25.73.94:3306/content_center
    hikari:
      username: root
      password: Wjh1234.
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 118.25.73.94:8848
  application:
    name: content-center
server:
  port: 8010
logging:
  config: classpath:logback-boot.xml
  level:
    cn.junhaox.contentcenter.feignclient.UserCenterFeignClient: debug
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
feign:
  client:
    config:
      user-center:
        loggerLevel: full
  httpclient:
    # 让feign使用HTTPClient，而不是默认的URLConnection
    enabled: true
    # feign的最大连接值
    max-connections: 200
    # feign单个路径的最大连接值
    max-connections-per-route: 50